### ISSUE TITLE
ciao-deploy: Passing the ssh key is not optional

### ISSUE THREAD

**Issue by albertomurillo** [clearlinux/dockerfiles#15]
ciao-deploy/README.md say is optional to pass the ssh key to the container.

This step is NOT optional since it is required by the container to login into the remote nodes.

**Comment by mrkz** [comment]
it does not mention to be optional, but instruct the user to use the key if it was ever setup (because it's not mentioned to create a key either in that README.md), so user could or not run the setup by using a key.

If we want to change to instruct to perform operations just using keys we also must create a step for the user to create a key and later make use of it.

**Comment by albertomurillo** [comment]
Maybe not include steps to create a key but mention a key is needed to login into the remote nodes because thats how ansible works.

If no private key is passed to the container then ansible will NOT be able to login into the remote nodes and thats a bug.

I dont think we should give the impression we can run the container without mapping the private key
