### ISSUE TITLE
`swupd search` doesn't work on stacks-pytorch-mkl docker image

### ISSUE THREAD

**Issue by ttzeng** [clearlinux/dockerfiles#180]
`swupd search` command throws the following error with the Pytorch-MKL docker image:
```
$ sudo docker run -it --rm clearlinux/stacks-pytorch-mkl
root@b808dffb8213 /workspace # swupd info
Installed version: 29800
Version URL:       https://cdn.download.clearlinux.org/update
Content URL:       https://cdn.download.clearlinux.org/update
root@b808dffb8213 /workspace # swupd search ffmpeg
Error: Binary /usr/bin/swupd-search doesn't exist in your system
```

**Comment by gorozco1** [comment]
@joselamego

**Comment by joselamego** [comment]
Thank you @ttzeng for reporting this. We will look at it and keep you updated.

**Comment by joselamego** [comment]
@ttzeng, we were able to replicate the issue you are reporting, however, it is caused by a missing message from `swupd` in Clear Linux OS version **29800** that should indicate why `swupd-search` is not available out-of-the-box, but can be easily installed:
```
Error: Binary /usr/bin/swupd-search doesn't exist in your system
Swupd search depends on a binary available on os-core-search bundle
Run 'swupd bundle-add os-core-search' to install it
```
This messsaging is included in newer Clear Linux OS versions, but you can already successfully add the required `os-core-search` bundle inside you container to have available `swupd search`.

Future releases of `clearlinux/stacks-pytorch-mkl` image will be based in newer Clear Linux OS versions and will feature the appropriate message.

Thanks for your report and for using the stack.
