### ISSUE TITLE
Add release version tagging on docker containers

### ISSUE THREAD

**Issue by bwarden** [clearlinux/dockerfiles#19]
Enhancement request: add tags for release versions to docker containers so it's easier to pull a specific version for testing/comparison.

**Comment by obedmr** [comment]
@bwarden, good point, we're implementing Travis CI to make sure we're doing the right thing. Thanks for the catch

**Comment by obedmr** [comment]
Travis CI integration was added for keystone container. https://travis-ci.org/clearlinux/dockerfiles.

It's making sure that keystone is working before triggering Dockerhub rebuild. There are also test that were implemented in the ClearLinux Project in order to make sure that Keystone packages are healthy. 

Adding tags would be good, but we'd like to keep one tag 'latest' and that will be the stable one.

**Comment by pskindel** [comment]
@obedmr Could you explain why have you decided to use one tag? It's not convenient, nor in accordance with Docker standards and well-known rules. Right now we are afraid of pulling your images from Docker Hub due to high risk of sudden change of these images' behavior. Everything may stop working properly because of sudden unexpected change of image in place of _latest_ tag.

**Comment by obedmr** [comment]
@pskindel sure, at that moment (almost 3 years ago) Clearlinux bundles were changing a lot and we didnt want to break cloud-related project like OpenStack Keystone.

Since OpenStack is not provided in ClearLinux anymore and also I have not involved in the Docker images build process, I'm not sure how it's going now.

I understand your concern and there should be a proper mechanism for images tagging. I'm not the one responsible for this right now.

@bwarden, @bryteise, @mrkz, @nesiusra  do you know who's in charge of ClearLinux-based images publishing? is there some documentation about the process?

**Comment by obedmr** [comment]
Adding @gtkramer

**Comment by nesiusra** [comment]
There are two reasons we only tag latest. The first is that we are a rolling release distro and release frequently. The second is that we don't want to continue distributing content with CVEs.  In the near future we may be exposing an LTS release of Clear that will likely meet your needs.
