### ISSUE TITLE
sdk: Account or Password Expired

### ISSUE THREAD

**Issue by shrmrf** [clearlinux/dockerfiles#35]
I built the [`clr-sdk`](https://github.com/clearlinux/dockerfiles/tree/master/clr-sdk) on my machine. When I go ahead and start the container, I get the following error(s):

```
sudo: Account or password is expired, reset your password and try again         
sudo: unable to change expired password: Authentication token manipulation error
```

They seem to stem from the [last line in `setup.py`](https://github.com/clearlinux/dockerfiles/blob/master/clr-sdk/setup.py#L78). If I use `su clr` instead, everything works fine.

This could perhaps be related to the fact that we're _not_ setting up the user's password anywhere in `setup.py`?

**Comment by mrkz** [comment]
@kevincwells

**Comment by shrmrf** [comment]
@mrkz did you try it out on your machine? @kevincwells seems to be away...

**Comment by shrmrf** [comment]
Ping!!

**Comment by kevincwells** [comment]
Ah wow, didn't see this til today -- sorry for the incredibly long delay! (For reference, I'm no longer working on the build tooling or related efforts, but it appears no one else has taken up maintainership of this container.)

I was indeed able to recreate this. Like you said, this happens when building locally, and is not experienced on the version on Dockerhub. The Dockerhub image is _supposed_ to have a build trigger set up to auto-build when its base (`clearlinux`) is rebuilt, but that doesn't appear to be working; the base image is only 22 days old, but the `clr-sdk` image is 3 months (still based on 21150!).

It's been quite some time, but IIRC the reason the password was not originally set up in `setup.py` is due to an issue with running `chpasswd` (the non-interactive password tool scripting it) within a Docker container when the network is shared with the host -- it accidentally reaches out to the host network PAM server and ends up failing.  Instead of setting a password, the `clr` user was granted sudoers `NOPASSWD` for just `mixer` and `swupd` (the only expected applications requiring sudo at the time it was created). Not that that helps with the current situation, just some context.

`su clr` does appear to work, and the difference to `sudo -H -u clr bash -i` here is pretty negligible -- both are going to set the`HOME` and launch an interactive shell in the correct directory.

**Comment by shrmrf** [comment]
In my version of the Dockerfile, I set the `root` user's password with `RUN echo -e "admin\nadmin" | passwd`

I also modify the `setup.py` file to add user to `wheel` group and the `clruser` file has:

```
clr ALL=NOPASSWD:SETENV: /usr/bin/mixer, /usr/bin/swupd
clr ALL=(ALL:ALL) NOPASSWD: ALL
%sudo ALL=(ALL:ALL) NOPASSWD: ALL
```

This fixes the problems I outlined above and then some. I can submit a PR later if that's useful..

**Comment by kevincwells** [comment]
@shrmrf  -- Glad you were able to work around the situation! 

A couple of observations:
- If you're going to have the second line in the `clruser` file, you might as well take out the first. The second line trumps the first, granting the `clr` user `NOPASSWD` access to every program, not just `mixer` and `swupd`. (The first is also granting `clr` the `SETENV` permission, in case you do plan on removing it).
  - If you'd like to give the `clr` user `NOPASSWD` access to run all applications as all users, you could instead just add the user to the `wheelnopw` group instead of `wheel`. The line in Clear's default `sodoers` file for `wheelnopw` (`%wheelnopw ALL=(ALL) NOPASSWD:ALL`) is subtly different in that it doesn't also have the group option for the `RUNAS` clause, but that likely won't affect you. 
- The third line in `clruser` shouldn't have any meaningful effect in Clear Linux, as the `sudo` group isn't a convention we use (it's from the Debian world).
  - While it's only really a convention, the intent of the `clruser` file was to set sudoers rules specific to the `clr` user. Thus, if you _did_ still want to have a line similar to the third line, it'd ideally live somewhere else. The default `sodoers` file (`/usr/share/defaults/sudo/sudoers`) in Clear Linux actually has that line in it already as one of the possible, commented-out templates.
- IIRC, the `echo -e "pass\npass" | passwd` approach fails on some systems (notably Debian-based) for the exact same reasons as `chpasswd` approach. (It might actually be limited only to Debian-based systems, but I'm not sure.) As the container was originally targeted as a portability solution for people running OS's like Ubuntu/Mint/etc., we had to leave that step out.

**Comment by shrmrf** [comment]
@kevincwells well, yeah, your observations are all correct IMO.. you can imagine the redundancy was due to my experimentation efforts. 

>IIRC, the echo -e "pass\npass" | passwd approach fails on some systems (notably Debian-based) for the exact same reasons as chpasswd approach. (It might actually be limited only to Debian-based systems, but I'm not sure.) As the container was originally targeted as a portability solution for people running OS's like Ubuntu/Mint/etc., we had to leave that step out.

It works for me as far as I can see. I'm on Ubuntu 16.04. You can check out my fork of the repo here:-
https://github.com/shrmrf/dockerfiles/tree/master/clr-sdk

Should I submit a PR after some cleanup?

**Comment by shrmrf** [comment]
@kevincwells does the latest `mixer` version `5.0.1` render this dockerfile useless?

_see: https://github.com/clearlinux/mixer-tools/issues/382_

**Comment by shrmrf** [comment]
Should we also close this issue thanks to https://github.com/clearlinux/dockerfiles/pull/36 ?

Without the `root` user's password set, we can't change to `root`:

```console
clr@88f255a2609d ~/mix $ sudo su -
You are required to change your password immediately (administrator enforced)
su: Authentication token manipulation error
```

I don't know if this is also a feature since we shouldn't need to `su -` if we're already a `sudoer`

**Comment by kevincwells** [comment]
> Should we also close this issue thanks to #36 ?

Yes, I believe #36 fixes this. @mrkz -- feel free to close this issue.

> I don't know if this is also a feature since we shouldn't need to `su -` if we're already a sudoer

Being in the `wheelnopw` group should eliminate the need to `su -`. If you still _need_ to become the root user, you can now set a password yourself. Alternatively, you can un-expire the root password by setting the "days since last password set" bit to something other than `0` in `/etc/shadow`. (By default, there is no `/etc/shadow` on Clear Linux; this value defaults in `/usr/share/defaults/etc/shadow`. You _could_ alter the bit here, but it'd be preferable to override this with a value in `/etc/shadow`.)

Personally, I feel becoming the root user is a practice that should be discouraged, as it often leads to commands being run as root when a) they don't need to, b) they shouldn't be (e.g., ownership issues), or c) it is dangerous to do so. Very few commands _need_ to be run as root. That said, I do recognize that a careful user can easily find convenience and benefit from becoming the root user for a period of time. At least now there's a path to that.

**Comment by shrmrf** [comment]
@kevincwells thanks for the comments. I totally agree!!
